### ISSUE TITLE
EBNF grammar - W3C style syntax

### ISSUE THREAD

**Issue by tpluscode** [picoe/Eto.Parse#12]
Coming back to my original issue.

Would it be a lot of work to implement a grammar, which parses the W3C EBNF syntax, decribed [here](http://www.w3.org/TR/REC-xml/#sec-notation)

I looked at the EbnfGrammar class, but there is a lot going on, seemingly much more than the bare mimimum...

**Comment by cwensley** [comment]
Now done in commit da03ae6724ba3a1cf94f3e95c75bfb0448eda5f2, and published to nuget in 1.4

**Comment by cwensley** [comment]
Thanks again for the suggestion!  Hopefully it works well for you.
