### ISSUE TITLE
dnx support

### ISSUE THREAD

**Issue by smbecker** [picoe/Eto.Parse#22]
I have used Eto.Parse in the past on a project with great success. I am starting a new project where I would like to leverage it again but the project will be using dnx and ASP vNext, which is currently not a supported platform for Eto.Parse. I have a local branch where I have started to add the basics to support the new project system in dnx. Currently, I have only updated the main project as the test projects are NUnit-based, which does not have any dnx-compatible libraries/runners yet. To do it right, I would probably need to port the tests to xunit. Is dnx something that you intend to support in the future? I could submit a PR if you would like.

**Comment by cwensley** [comment]
Wow great to hear you've had some good experiences with Eto.Parse!

I had no plans to add dnx support, but I would certainly welcome it.

**Comment by cwensley** [comment]
Eto.Parse supports net standard 2.0 and net45, which should allow it to run nearly anywhere.
