### ISSUE TITLE
[Req] navigating with XPath

### ISSUE THREAD

**Issue by ArsenShnurkov** [picoe/Eto.Parse#27]
XPath uses path expressions to select nodes or node-sets.

brief introduction:
http://www.w3schools.com/xsl/xpath_syntax.asp

EBNF-like grammar:
http://www.w3.org/TR/xquery-xpath-parsing/#id-grammar

.net class library contains a set of classes and interfaces which automates that.
(starting from System.Xml.XPath, IXPathNavigable )

I propose to implement such access to the tree of Match-es, which are returned as result of parsing

**Comment by furesoft** [comment]
good idea

**Comment by ArsenShnurkov** [comment]
http://stackoverflow.com/questions/2324432/using-an-xpath-style-query-with-reflection

**Comment by ArsenShnurkov** [comment]
http://goessner.net/articles/JsonPath/

<table><tbody><tr class="evn"><td> <strong>XPath</strong> </td><td> <strong>JSONPath</strong> </td><td> <strong>Description</strong> </td></tr>
<tr class="odd"><td> / </td><td> $ </td><td class="lft">the root object/element </td></tr>
<tr class="evn"><td> . </td><td> @ </td><td class="lft">the current object/element </td></tr>
<tr class="odd"><td> / </td><td> . or [] </td><td class="lft">child operator </td></tr>
<tr class="evn"><td> .. </td><td> n/a </td><td class="lft">parent operator </td></tr>
<tr class="odd"><td> // </td><td> .. </td><td class="lft">recursive descent. JSONPath borrows this syntax from E4X. </td></tr>
<tr class="evn"><td> * </td><td> * </td><td class="lft">wildcard. All objects/elements regardless their names. </td></tr>
<tr class="odd"><td> @ </td><td> n/a </td><td class="lft">attribute access. JSON structures don't have attributes. </td></tr>
<tr class="evn"><td> [] </td><td> [] </td><td class="lft">subscript operator. XPath uses it to iterate over element collections and for <a href="http://www.w3.org/TR/xpath#predicates">predicates</a>. In Javascript and JSON it is the native array operator. </td></tr>
<tr class="odd"><td> | </td><td> [,] </td><td class="lft">Union operator in XPath results in a combination of node sets. JSONPath allows alternate names or array indices as a set. </td></tr>
<tr class="evn"><td> n/a </td><td> [start:&zwnj;end:step] </td><td class="lft">array slice operator borrowed from ES4. </td></tr>
<tr class="odd"><td> [] </td><td> ?() </td><td class="lft">applies a filter (script) expression. </td></tr>
<tr class="evn"><td> n/a </td><td> () </td><td class="lft">script expression, using the underlying script engine. </td></tr>
<tr class="odd"><td> () </td><td> n/a </td><td class="lft">grouping in Xpath </td></tr></tbody></table>

**Comment by ArsenShnurkov** [comment]
https://www.sitepen.com/blog/2010/11/02/resource-query-language-a-query-language-for-the-web-nosql/

RQL is designed to be URI friendly, leveraging URI encoding and designated delimiters for syntax that works perfectly in web requests.
RQL is designed to be extensible.
