### ISSUE TITLE
[Q] Is Grammar/Parser Threadsafe

### ISSUE THREAD

**Issue by AndyPook** [picoe/Eto.Parse#30]
Just looking for confirmation... It is possible to create a Grammar as a singleton then have many threads concurrently parsing many strings? (This is the purpose of ParseArgs)

**Comment by cwensley** [comment]
Hi @AndyPook, yes it should be thread safe.  Some of the grammars in eto (e.g. EbnfGrammar, GoldGrammar, etc) are not thread safe but could be made to be.

**Comment by AndyPook** [comment]
Thanks.
Probably wouldn't be worth the effort as they would probably only be required to bootstrap the singleton.

**Comment by cwensley** [comment]
Exactly (;

One thing I forgot though, is that upon first use of a grammar, it goes through an initialization phase to optimize and fix left recursive grammars, etc.  This is not thread safe as it updates the grammar structure.  You can do this manually by calling Grammar.Initialize() after construction, and all should be good.
