### ISSUE TITLE
EBNF parsing doesn't work

### ISSUE THREAD

**Issue by themightylc** [picoe/Eto.Parse#38]
I can't get any EBNF parsing to work at all. Neither custom examples or samples used in the unit tests.

**Comment by cwensley** [comment]
Hey @themightylc,

It is not active, which is different from being "dead".  I would actively accept any PR's, though none have come my way.

If you would post an example of what you have tried and what does not work, perhaps I can help.

**Comment by themightylc** [comment]
Thank you for responding. I made the parser I needed with with ANTLR moths ago. You can close this issue.

**Comment by cwensley** [comment]
@themightylc awesome, ANTLR is a great option.  Thanks for the update.
