### ISSUE TITLE
Letter parser accepts all Unicode letters as a letter

### ISSUE THREAD

**Issue by archfrog** [picoe/Eto.Parse#49]
Not sure if this is a bug, but the code below accepts all Unicode letters as letters - i.e. Hebrew, Cyrillic, etc.:

[Eto.Parse.Parsers.LetterTerminal.Test, Char.IsLetter() test](https://github.com/picoe/Eto.Parse/blob/f9f16e0c380bc53a69bd4d6874c0fa728bbf2e98/Eto.Parse/Parsers/LetterTerminal.cs#L19)

My guess is that is should have been an explicit check for the ranges 'a'..'z' and 'A'..'Z' (ASCII letters).

If not, please close this issue - I just stumbled across the above and wanted to make sure it was intentional.

**Comment by cwensley** [comment]
Yes, this is correct.  Those are actually letters! even though they are not _english_ letters.

If you only want a-z and A-Z, try using the CharRangeTerminal.

**Comment by archfrog** [comment]
Thanks for the clarification and the new stuff :-)
